source 'https://rubygems.org'

gem 'rake'
gem 'mocha'
gem 'diff-lcs'
gem 'json_pure'
gem 'json'
gem 'metadata-json-lint'
gem 'puppet-lint', '1.1.0'
gem 'rspec-puppet', '2.2.0'
gem 'puppet', '>4'
gem 'puppetlabs_spec_helper', '0.10.3'
